#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

echo "Cleaning..."

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd Fluid j
    cleanCase
    rm -rfv 0
    touch {Participant1}.foam
cd ..

# Remove the log files
rm -fv *.log

cd Solid 
    #Clean the case
	rm -fv *.bnd
	rm -fv *.lds
	rm -fv *.d
	rm -fv *.dat
cd ..

# Remove the preCICE-related log files
rm -fv \
    precice-*.log \
    precice-postProcessingInfo.log
    
echo "Cleaning complete!"
#------------------------------------------------------------------------------
