#!/usr/bin/env bash

# Run from this directory
cd ${0%/*} || exit 1    

echo "Cleaning..."

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cd Fluid 
    # Clean the case
    cleanCase
cd ..

cd Solid
    # Clean the case files
    rm -vf *.bnd
    rm -vf *.d
    rm -vf *.dat
    rm -vf *.lds
    rm -vf *.int
    rm -vf *.fix
    rm -vf *.nset
    rm -vf *.ensi.*
cd ..

# Remove the log files
rm -fv log.blockMesh
rm -fv log.snappyHexMesh
rm -fv log.checkMesh

echo "Cleaning complete!"
#------------------------------------------------------------------------------
